[GOV-261] Logging client IP
openMF/ph-ee-connector-channel pull request #102
Opened 2023-06-07 11:24 UTC by truthfool

## Description
- Logging client Ip in channel connector.

Steps : https://docs.google.com/document/d/1-PgOwUsM77cbpipI81ZRHt4t9gnQ4ryXsEyRSg4m-lM/edit?usp=sharing

Jira Ticket : https://mifosforge.jira.com/jira/software/c/projects/GOV/issues/GOV-261?jql=project%20%3D%20%22GOV%22%20AND%20assignee%20%3D%20%2261cd59bef3037f0069bc0572%22%20ORDER%20BY%20created%20DESC
 _(Ignore if these details are present on the associated JIRA ticket)_

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design related bullet points or design document link related to this PR added in the description above. 

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-06-07 11:28 UTC, truthfool commented
@fynmanoj @avikganguly01

2023-06-08 11:25 UTC, fynmanoj requested changes

2023-06-08 11:25 UTC, fynmanoj commented on src/main/java/org/mifos/connector/gsmastub/api/ApiOriginFilter.java
> +        logger.debug("Client IP Address: {}",req.getRemoteHost());
This can be info-level log

2023-06-14 13:07 UTC, fynmanoj approved these changes

2023-06-14 13:07 UTC, merged