Parameterize collection payment scheme
openMF/ph-ee-connector-channel pull request #115
Opened 2023-07-27 12:42 UTC by victorjbassey

## Description

In addition to Mpesa, other similar flows (ex. Airtel Money, MTN MoMo, etc) can be supported by parameterizing the payment scheme.

This PR adds support for an optional `X-PaymentScheme` header whose value will determine which bpmn flow will be started when a collection request is received.

@avikganguly01 @fynmanoj @ankita10r please review

2023-07-28 06:27 UTC, truthfool commented
Hi @victorjbassey Can you create a JIRA Ticket for the pull request. It will not be reviewed/merged unless a Jira Ticket is present. If you are not able to create a JIRA ticket pls reach out to @fynmanoj or @avikganguly01 .

2023-07-28 08:28 UTC, victorjbassey commented
> Hi @victorjbassey Can you create a JIRA Ticket for the pull request. It will not be reviewed/merged unless a Jira Ticket is present. If you are not able to create a JIRA ticket pls reach out to @fynmanoj or @avikganguly01 .

Hi @truthfool 
Can you share the link to where I can create the ticket?

2023-07-28 09:44 UTC, truthfool commented
https://mifosforge.jira.com/jira/software/c/projects/PHEE/issues

2023-08-08 15:12 UTC, avikganguly01 requested changes

2023-08-08 15:12 UTC, avikganguly01 commented on src/main/java/org/mifos/connector/channel/camel/config/CamelProperties.java
> +    public static final String PAYMENT_SCHEME_HEADER = "X-PaymentScheme";
API Guidelines indicate that new headers have to follow hyphen separated naming convention like X-Payment-Scheme.

2023-08-08 15:18 UTC, avikganguly01 requested changes
@Victor Bassey :
The pipelines have ran and they are successful. Please follow coding conventions by following this guide - https://github.com/apache/fineract#checkstyle-and-spotless 
Use the gradle license plugin to add license header to any newly added files in future PRs. 

Please write an [integration test](https://github.com/openMF/ph-ee-integration-test) to prevent others from breaking your code. Scope of what has to be deployed in order for your integration test to pass has to be carefully designed. Ex:- If test case is dependent on a specific AMS which is not deployed in CircleCI scripts, the test case will fail. 

Perhaps a simple scope could be an unit test instead of an integration test here to see if PS is resolved which is a prerequisite for orchestration configuration to be resolved.

2023-08-09 14:35 UTC, victor commented
@avikganguly01 please watch your mentions. thanks

2023-08-18 05:49 UTC, fynmanoj approved these changes

2023-08-28 11:51 UTC, merged