Hosting
openMF/ph-ee-connector-channel pull request #126
Opened 2023-08-11 05:43 UTC by dhruvsonagara

## Description

[PHEE-386 Update circle CI config of micro services with integration test](https://fynarfin.atlassian.net/browse/PHEE-386?atlOrigin=eyJpIjoiZjczZjdlOWI5MTA1NDgyN2I3OTQ4M2NiMzk5ZTVkMGYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design related bullet points or design document link related to this PR added in the description above.

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-08-14 11:01 UTC, arkadasfynarfin commented
@dhruvsonagara Looks good to me.
CC: @fynmanoj

2023-08-18 05:38 UTC, fynmanoj requested changes
Can you check circle ci orn creation and may be try to avoid these code duplications?

2023-08-18 05:38 UTC, fynmanoj commented on .circleci/config.yml
> +            ./gradlew bootJar
Don't remove build , make sure that checkstyles are executed

2023-08-18 05:38 UTC, fynmanoj commented on .circleci/config.yml
> +          kubectl config use-context arn:aws:eks:$REGION:$ACCOUNT_ID:cluster/sit
For bulk, ams mifos, channel and ops app, the restart logic is already added. You can skip this

2023-08-18 05:38 UTC, fynmanoj commented on .circleci/config.yml
> +      - run: rm -f helm/g2p-sandbox/Chart.lock helm/g2p-sandbox/requirements.lock helm/g2p-sandbox/charts/*
Here you have to give proper path. Else it won't work with got clone

2023-08-18 05:38 UTC, fynmanoj commented on .circleci/config.yml
> +      - run: rm -f helm/g2p-sandbox/Chart.lock helm/g2p-sandbox/requirements.lock helm/g2p-sandbox/charts/*
Suggestion: use ph-ee-env-template in the path

2023-09-01 10:46 UTC, fynmanoj approved these changes

2023-09-01 10:47 UTC, merged