Added field NOTE with value of description for Payee deposit API
openMF/ph-ee-connector-channel pull request #53
Opened 2023-01-20 12:49 UTC by dhruvsonagara

## Description

1. Added the field Note which is passed as zeebe variable in zeeberworkflow.
2. Which is called in the AMS mifos Deposit API via zeebeworkers.

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Design related bullet points or design document link related to this PR added in the description above. 

- [x] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [x] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-01-20 12:52 UTC, danishjamal104 requested changes
Just remove the commented code rest everything looks good to me.

2023-01-20 12:52 UTC, danishjamal104 commented on src/main/java/org/mifos/connector/channel/camel/routes/GSMAChannelRouteBuilder.java
> +//                    String note = exchange.getIn().getBody("note", String.class);
Please remove the commented out code.

2023-01-20 13:40 UTC, fynmanoj approved these changes

2023-01-23 07:01 UTC, danishjamal104 approved these changes

2023-02-07 05:54 UTC, merged