Added loggers for tenant in filters
openMF/ph-ee-connector-channel pull request #86
Opened 2023-04-18 12:31 UTC by truthfool

## Description

- Logged tenant in filters
Jira Ticket GOV- 265 : https://mifosforge.jira.com/browse/GOV-265

 _(Ignore if these details are present on the associated JIRA ticket)_

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design related bullet points or design document link related to this PR added in the description above. 

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-04-18 12:31 UTC, truthfool commented
@fynmanoj @avikganguly01

2023-05-09 07:33 UTC, fynmanoj requested changes
changes requested

2023-05-09 07:33 UTC, fynmanoj commented on src/main/java/org/mifos/connector/gsmastub/api/ApiOriginFilter.java
> +//        Enumeration<String> stringEnum=req.getAttributeNames();
remove commented lines

2023-05-09 07:33 UTC, fynmanoj commented on src/main/java/org/mifos/connector/gsmastub/api/ApiOriginFilter.java
> +        String tenant = req.getHeader("Platform-TenantId");
create string constants for the literals

2023-05-09 07:33 UTC, fynmanoj commented on src/main/java/org/mifos/connector/gsmastub/api/ApiOriginFilter.java
> +            logger.info("Tenant Name is : {}", tenant);
This looks like an unnecessary wrapping. what is the use of creating the optional wrapper, when you already have the object? try methods like `nonNull(foo)`.  logging empty tenant is also fine IMO

2023-05-09 07:33 UTC, fynmanoj commented on src/main/resources/application.yml
> +dfspids: "gorilla"
this change can be done from deployment, it is not necessary to be part of the code.

2023-05-09 07:33 UTC, fynmanoj commented on src/main/java/org/mifos/connector/gsmastub/api/ApiOriginFilter.java
> +                logger.info(ip);
the logger is very vague, please add text to mention what header you are logging, it will be difficult to process these lines by a log aggregator.

2023-05-09 07:33 UTC, fynmanoj commented on src/main/java/org/mifos/connector/gsmastub/api/ApiOriginFilter.java
> +            if (ip != null && ip.length() != 0 && !"unknown".equalsIgnoreCase(ip)) {
suggestion:  these kind of null checks are considered low level checks, these can be replaced by stringutil functions like `isNotBlank()`

2023-05-23 09:32 UTC, fynmanoj requested changes

2023-05-23 09:32 UTC, fynmanoj commented on src/main/java/org/mifos/connector/gsmastub/api/ApiOriginFilter.java
> +        if (!tenant.isEmpty()) {
you don't need this check

2023-06-01 07:19 UTC, fynmanoj approved these changes

2023-06-01 07:19 UTC, merged